LOREM_IPSUM_TEXT1 = """Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. 

	Donec enim diam vulputate ut pharetra sit amet. Sit amet aliquam id diam maecenas. Ornare lectus sit amet est placerat in egestas. Eu volutpat odio facilisis mauris.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Consequat nisl vel pretium lectus quam. Vitae congue eu consequat ac felis donec et odio. Sed lectus vestibulum mattis ullamcorper velit sed ullamcorper morbi. Senectus et netus et malesuada fames ac turpis egestas."""

LOREM_IPSUM_TEXT2 = """Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Pulvinar pellentesque habitant morbi tristique senectus et netus et malesuada. Neque gravida in fermentum et. Pellentesque id nibh tortor id aliquet lectus proin. In tellus integer feugiat scelerisque. In nibh mauris cursus mattis molestie. Commodo ullamcorper a lacus vestibulum sed arcu non odio euismod. Turpis egestas sed tempus urna et pharetra pharetra. Vitae elementum curabitur vitae nunc sed velit dignissim sodales. Egestas pretium aenean pharetra magna ac placerat vestibulum lectus mauris. Fringilla urna porttitor rhoncus dolor purus non enim praesent elementum. Ut tristique et egestas quis.

Semper auctor neque vitae tempus quam pellentesque. Tempor commodo ullamcorper a lacus vestibulum sed arcu non. Aliquet nec ullamcorper sit amet risus nullam eget. Id venenatis a condimentum vitae sapien pellentesque habitant morbi. Nisl nunc mi ipsum faucibus. Auctor eu augue ut lectus arcu. Dictum varius duis at consectetur lorem donec. Suspendisse interdum consectetur libero id faucibus. Et pharetra pharetra massa massa ultricies mi quis. Phasellus vestibulum lorem sed risus.

Vestibulum lorem sed risus ultricies. Mauris pharetra et ultrices neque ornare aenean. Augue eget arcu dictum varius duis at consectetur lorem. Donec adipiscing tristique risus nec feugiat in fermentum posuere urna. At imperdiet dui accumsan sit amet. Pellentesque pulvinar pellentesque habitant morbi tristique senectus. Rhoncus urna neque viverra justo nec ultrices dui. Ultrices sagittis orci a scelerisque purus semper eget. Dictum at tempor commodo ullamcorper a. Risus nec feugiat in fermentum. Ipsum faucibus vitae aliquet nec ullamcorper sit amet risus. Et ligula ullamcorper malesuada proin libero nunc. Purus gravida quis blandit turpis cursus in hac.

Rhoncus dolor purus non enim praesent. Odio aenean sed adipiscing diam donec. Non sodales neque sodales ut etiam sit. Vel eros donec ac odio tempor orci dapibus. Phasellus faucibus scelerisque eleifend donec. Blandit cursus risus at ultrices mi tempus. Vehicula ipsum a arcu cursus vitae congue mauris rhoncus. Ut tristique et egestas quis ipsum suspendisse ultrices gravida. Leo urna molestie at elementum eu. Mi quis hendrerit dolor magna eget est lorem ipsum dolor. Cursus in hac habitasse platea dictumst quisque. Ut porttitor leo a diam sollicitudin. Dignissim convallis aenean et tortor at risus viverra. Velit ut tortor pretium viverra.

Ornare lectus sit amet est placerat in egestas erat. Dolor morbi non arcu risus quis varius quam. Non blandit massa enim nec dui nunc mattis enim ut. Malesuada fames ac turpis egestas maecenas pharetra convallis posuere. At consectetur lorem donec massa sapien faucibus et molestie ac. Urna porttitor rhoncus dolor purus non. Laoreet non curabitur gravida arcu ac tortor dignissim convallis. Facilisi nullam vehicula ipsum a arcu cursus vitae. Amet nisl suscipit adipiscing bibendum. Nibh tellus molestie nunc non blandit massa enim nec dui. Est velit egestas dui id. Vitae proin sagittis nisl rhoncus mattis rhoncus urna. Nam aliquam sem et tortor consequat id porta nibh. Scelerisque purus semper eget duis at. Sollicitudin nibh sit amet commodo nulla facilisi nullam vehicula ipsum. Sit amet consectetur adipiscing elit duis. Consequat semper viverra nam libero justo laoreet sit.


Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Id neque aliquam vestibulum morbi blandit cursus risus at ultrices. Dignissim enim sit amet venenatis urna cursus. Sed risus ultricies tristique nulla aliquet. Turpis egestas maecenas pharetra convallis posuere morbi leo. Id neque aliquam vestibulum morbi blandit cursus risus at ultrices. Dignissim enim sit amet venenatis urna cursus.

Ornare lectus sit amet est placerat in egestas erat. Dolor morbi non arcu risus quis varius quam. Non blandit massa enim nec dui nunc mattis enim ut. Malesuada fames ac turpis egestas maecenas pharetra convallis posuere. At consectetur lorem donec massa sapien faucibus et molestie ac. Urna porttitor rhoncus dolor purus non. Laoreet non curabitur gravida arcu ac tortor dignissim convallis. Facilisi nullam vehicula ipsum a arcu cursus vitae. Amet nisl suscipit adipiscing bibendum. Nibh tellus molestie nunc non blandit massa enim nec dui. Est velit egestas dui id. Vitae proin sagittis nisl rhoncus mattis rhoncus urna. Nam aliquam sem et tortor consequat id porta nibh. Scelerisque purus semper eget duis at. Sollicitudin nibh sit amet commodo nulla facilisi nullam vehicula ipsum. Sit amet consectetur adipiscing elit duis. Consequat semper viverra nam libero justo laoreet sit.
"""

LOREM_IPSUM_TEXT3 = """Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Tincidunt lobortis feugiat vivamus at augue eget. Quisque egestas diam in arcu cursus euismod quis viverra. Dolor sit amet consectetur adipiscing elit pellentesque. Orci ac auctor augue mauris augue neque gravida."""